# Maximum number of papers to publish in a given run
# If this value is zero, all new papers matching the criteria are published
# Default value: 0
throttle: 10

# Time (in seconds) to wait between two tweets
# Default value: 5
wait_time: 30

# Should the feed list be randomly shuffled?
# Avoids tweeting always the same journals first/last
# Default value: true
shuffle_feeds: true

# URLs matching these regular expressions will not be tweeted
# Used e.g. for Wiley journals that republish old content with new URLs
blacklist:
  - "pericles.pericles-prod.literatumonline.com"
  - "www.onlinelibrary.wiley.com"
